### ISSUE TITLE
Support front matter in mdx

### ISSUE THREAD

**Issue by chenxsan** [chenxsan/voidjs#486]
Say we have front matter in mdx like below:

```yml
---
title: hello voidjs
description: this is voidjs
---
```
It should be transformed into:

```js
export async function getStaticProps() {
  return {
    props: {
      title: 'hello voidjs',
      description: 'this is voidjs',
    },
  }
}
```
